### ISSUE TITLE
XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed

### ISSUE THREAD

**Issue by Yung-Chien** [jthlab/phlash#31]
when I tried to run my test data on gpu(Nvidia Tesla V100), I got this error,

E1110 19:12:18.304984    4203 cuda_dnn.cc:502] There was an error before creating cudnn handle (35): cudaErrorInsufficientDriver : CUDA driver version is insufficient for CUDA runtime version
E1110 19:12:18.305494    4203 cuda_dnn.cc:502] There was an error before creating cudnn handle (35): cudaErrorInsufficientDriver : CUDA driver version is insufficient for CUDA runtime version

---------------------------------------------------------------------------
XlaRuntimeError                           Traceback (most recent call last)
Cell In[7], line 1
----> 1 results = phlash.fit(chroms_1kg, mutation_rate=2.9e-9)

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/phlash/mcmc.py:68, in fit(data, test_data, **options)
     66 _check_jax_gpu()
     67 # some defaults pulled from the options dict
---> 68 key = options.get("key", jax.random.PRNGKey(1))
     69 # the number of svgd iterations. if a test dataset is provided, the optimizer
     70 # might perform fewer if convergence criteria are met.
     71 niter = options.get("niter", 1000)

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/jax/_src/random.py:246, in PRNGKey(seed, impl)
    220 def PRNGKey(seed: int | ArrayLike, *,
    221             impl: PRNGSpecDesc | None = None) -> Array:
    222   """Create a legacy PRNG key given an integer seed.
    223 
    224   This function produces old-style legacy PRNG keys, which are arrays
   (...)    244     and ``fold_in``.
    245   """
--> 246   return _return_prng_keys(True, _key('PRNGKey', seed, impl))

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/jax/_src/random.py:198, in _key(ctor_name, seed, impl_spec)
    194 if np.ndim(seed):
    195   raise TypeError(
    196       f"{ctor_name} accepts a scalar seed, but was given an array of "
    197       f"shape {np.shape(seed)} != (). Use jax.vmap for batching")
--> 198 return prng.random_seed(seed, impl=impl)

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/jax/_src/prng.py:532, in random_seed(seeds, impl)
    527 def random_seed(seeds: int | typing.ArrayLike, impl: PRNGImpl) -> PRNGKeyArray:
    528   # Avoid overflow error in X32 mode by first converting ints to int64.
    529   # This breaks JIT invariance for large ints, but supports the common
    530   # use-case of instantiating with Python hashes in X32 mode.
    531   if isinstance(seeds, int):
--> 532     seeds_arr = jnp.asarray(np.int64(seeds))
    533   else:
    534     seeds_arr = jnp.asarray(seeds)

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/jax/_src/numpy/lax_numpy.py:5721, in asarray(a, dtype, order, copy, device)
   5719 if dtype is not None:
   5720   dtype = dtypes.canonicalize_dtype(dtype, allow_extended_dtype=True)  # type: ignore[assignment]
-> 5721 return array(a, dtype=dtype, copy=bool(copy), order=order, device=device)

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/jax/_src/numpy/lax_numpy.py:5555, in array(object, dtype, copy, order, ndmin, device)
   5553 else:
   5554   raise TypeError(f"Unexpected input type for array: {type(object)}")
-> 5555 out_array: Array = lax_internal._convert_element_type(
   5556     out, dtype, weak_type=weak_type, sharding=sharding)
   5557 if ndmin > np.ndim(out_array):
   5558   out_array = lax.expand_dims(out_array, range(ndmin - np.ndim(out_array)))

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/jax/_src/lax/lax.py:1614, in _convert_element_type(operand, new_dtype, weak_type, sharding, warn_on_complex_to_real_cast)
   1612   return operand
   1613 else:
-> 1614   return convert_element_type_p.bind(
   1615       operand, new_dtype=new_dtype, weak_type=bool(weak_type),
   1616       sharding=sharding)

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/jax/_src/core.py:502, in Primitive.bind(self, *args, **params)
    500 def bind(self, *args, **params):
    501   args = args if self.skip_canonicalization else map(canonicalize_value, args)
--> 502   return self._true_bind(*args, **params)

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/jax/_src/core.py:520, in Primitive._true_bind(self, *args, **params)
    518 trace_ctx.set_trace(eval_trace)
    519 try:
--> 520   return self.bind_with_trace(prev_trace, args, params)
    521 finally:
    522   trace_ctx.set_trace(prev_trace)

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/jax/_src/lax/lax.py:4701, in _convert_element_type_bind_with_trace(trace, args, params)
   4699 def _convert_element_type_bind_with_trace(trace, args, params):
   4700   sharding = params['sharding']
-> 4701   operand = core.Primitive.bind_with_trace(convert_element_type_p, trace, args, params)
   4702   if sharding is not None and sharding._is_concrete:
   4703     with core.set_current_trace(trace):

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/jax/_src/core.py:525, in Primitive.bind_with_trace(self, trace, args, params)
    524 def bind_with_trace(self, trace, args, params):
--> 525   return trace.process_primitive(self, args, params)

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/jax/_src/core.py:1029, in EvalTrace.process_primitive(self, primitive, args, params)
   1027       return primitive.bind_with_trace(arg._trace, args, params)
   1028 check_eval_args(args)
-> 1029 return primitive.impl(*args, **params)

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/jax/_src/dispatch.py:88, in apply_primitive(prim, *args, **params)
     86 prev = lib.jax_jit.swap_thread_local_state_disable_jit(False)
     87 try:
---> 88   outs = fun(*args)
     89 finally:
     90   lib.jax_jit.swap_thread_local_state_disable_jit(prev)

    [... skipping hidden 11 frame]

File ~/miniconda3/envs/phlash/lib/python3.13/site-packages/jax/_src/compiler.py:321, in backend_compile(backend, module, options, host_callbacks)
    315     return backend.compile(
    316         built_c, compile_options=options, host_callbacks=host_callbacks
    317     )
    318   # Some backends don't have `host_callbacks` option yet
    319   # TODO(sharadmv): remove this fallback when all backends allow `compile`
    320   # to take in `host_callbacks`
--> 321   return backend.compile(built_c, compile_options=options)
    322 except xc.XlaRuntimeError as e:
    323   for error_handler in _XLA_RUNTIME_ERROR_HANDLERS:

XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

So how could I solve this problem?

**Comment by terhorst** [comment]
This indicates a configuration issue with CUDA and/or Jax. Please see https://github.com/jax-ml/jax/issues/15361 for tips on how to debug this.

**Comment by Yung-Chien** [comment]
I solved this issue by upgrading the NVIDIA Drivers in my server, Thanks you very much!
